//$file${SMs::./Inc::bt_SPC51_SM.h} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: bt_SPC5x_SM.qm
// File:  ${SMs::./Inc::bt_SPC51_SM.h}
//
// This code has been generated by QM 7.0.1 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// Copyright (c) 2005 Quantum Leaps, LLC. All rights reserved.
//
//                 ____________________________________
//                /                                   /
//               /    GGGGGGG    PPPPPPPP   LL       /
//              /   GG     GG   PP     PP  LL       /
//             /   GG          PP     PP  LL       /
//            /   GG   GGGGG  PPPPPPPP   LL       /
//           /   GG      GG  PP         LL       /
//          /     GGGGGGG   PP         LLLLLLL  /
//         /___________________________________/
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open-source software licensed under the GNU
// General Public License (GPL) as published by the Free Software Foundation
// (see <https://www.gnu.org/licenses>).
//
// NOTE:
// The GPL does NOT permit the incorporation of this code into proprietary
// programs. Please contact Quantum Leaps for commercial licensing options,
// which expressly supersede the GPL and are designed explicitly for
// closed-source distribution.
//
// Quantum Leaps contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${SMs::./Inc::bt_SPC51_SM.h} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#ifndef remoteSM_H_
#define remoteSM_H_

//extern QHsm * const the_oven;

//$declare(SMs::INITIAL_FLAG_CONFIG)
//$declare${SMs} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${SMs::bt_SPC51} ...........................................................
typedef struct {
// protected:
    QMsm super;

// private:
    sl_status_t sc;
    uint8_t advertising_set_handle;
    bd_addr address;
    uint8_t address_type;
    uint8_t system_id[8];
    uint8_t section;
    uint32_t TargetAddress;
    uint16_t ui16BytesToWrite;
    uint8_t * data;
    uint8_t bsl_pwd [32];
    uint8_t update_connection;
} bt_SPC51;

// public:
void bt_SPC51_ctor(bt_SPC51 * const me);

// private:
void bt_SPC51_Host_BSL_writeMemory(bt_SPC51 * const me);

// protected:
QState bt_SPC51_initial(bt_SPC51 * const me, void const * const par);
QState bt_SPC51_INITIALIZING  (bt_SPC51 * const me, QEvt const * const e);
extern QMState const bt_SPC51_INITIALIZING_s;
QState bt_SPC51_OPERRATIONAL  (bt_SPC51 * const me, QEvt const * const e);
QState bt_SPC51_OPERRATIONAL_e(bt_SPC51 * const me);
QState bt_SPC51_OPERRATIONAL_i(bt_SPC51 * const me);
extern QMState const bt_SPC51_OPERRATIONAL_s;
QState bt_SPC51_ADVERTISING  (bt_SPC51 * const me, QEvt const * const e);
QState bt_SPC51_ADVERTISING_e(bt_SPC51 * const me);
extern QMState const bt_SPC51_ADVERTISING_s;
QState bt_SPC51_MANAGING_CONNECTION  (bt_SPC51 * const me, QEvt const * const e);
QState bt_SPC51_MANAGING_CONNECTION_e(bt_SPC51 * const me);
extern QMState const bt_SPC51_MANAGING_CONNECTION_s;
QState bt_SPC51_FIRMWARE_UPDATE  (bt_SPC51 * const me, QEvt const * const e);
QState bt_SPC51_FIRMWARE_UPDATE_x(bt_SPC51 * const me);
QState bt_SPC51_FIRMWARE_UPDATE_i(bt_SPC51 * const me);
extern QMState const bt_SPC51_FIRMWARE_UPDATE_s;
QState bt_SPC51_SEND_CONN  (bt_SPC51 * const me, QEvt const * const e);
QState bt_SPC51_SEND_CONN_e(bt_SPC51 * const me);
QState bt_SPC51_SEND_CONN_x(bt_SPC51 * const me);
extern QMState const bt_SPC51_SEND_CONN_s;
QState bt_SPC51_GET_DEV_INFO  (bt_SPC51 * const me, QEvt const * const e);
QState bt_SPC51_GET_DEV_INFO_e(bt_SPC51 * const me);
QState bt_SPC51_GET_DEV_INFO_x(bt_SPC51 * const me);
extern QMState const bt_SPC51_GET_DEV_INFO_s;
QState bt_SPC51_UNLOCK  (bt_SPC51 * const me, QEvt const * const e);
QState bt_SPC51_UNLOCK_e(bt_SPC51 * const me);
QState bt_SPC51_UNLOCK_x(bt_SPC51 * const me);
extern QMState const bt_SPC51_UNLOCK_s;
QState bt_SPC51_UNLOCKED  (bt_SPC51 * const me, QEvt const * const e);
QState bt_SPC51_UNLOCKED_i(bt_SPC51 * const me);
extern QMState const bt_SPC51_UNLOCKED_s;
QState bt_SPC51_MASS_ERASE  (bt_SPC51 * const me, QEvt const * const e);
QState bt_SPC51_MASS_ERASE_e(bt_SPC51 * const me);
QState bt_SPC51_MASS_ERASE_x(bt_SPC51 * const me);
extern QMState const bt_SPC51_MASS_ERASE_s;
QState bt_SPC51_PROGRAM_SECTION  (bt_SPC51 * const me, QEvt const * const e);
QState bt_SPC51_PROGRAM_SECTION_e(bt_SPC51 * const me);
QState bt_SPC51_PROGRAM_SECTION_x(bt_SPC51 * const me);
extern QMState const bt_SPC51_PROGRAM_SECTION_s;
QState bt_SPC51_START_APP  (bt_SPC51 * const me, QEvt const * const e);
QState bt_SPC51_START_APP_e(bt_SPC51 * const me);
QState bt_SPC51_START_APP_x(bt_SPC51 * const me);
extern QMState const bt_SPC51_START_APP_s;
QState bt_SPC51_BAUDRATE  (bt_SPC51 * const me, QEvt const * const e);
QState bt_SPC51_BAUDRATE_e(bt_SPC51 * const me);
extern QMState const bt_SPC51_BAUDRATE_s;
QState bt_SPC51_PROG_VERIFICATION  (bt_SPC51 * const me, QEvt const * const e);
QState bt_SPC51_PROG_VERIFICATION_e(bt_SPC51 * const me);
extern QMState const bt_SPC51_PROG_VERIFICATION_s;
QState bt_SPC51_CheckStaus  (bt_SPC51 * const me, QEvt const * const e);
QState bt_SPC51_CheckStaus_e(bt_SPC51 * const me);
QState bt_SPC51_CheckStaus_x(bt_SPC51 * const me);
extern QMState const bt_SPC51_CheckStaus_s;

//${SMs::bt_SPC51_inst} ......................................................
extern bt_SPC51 bt_SPC51_inst;

//${SMs::INITIAL_FLAG_CONFIG} ................................................
#define INITIAL_FLAG_CONFIG 0b00101010

//${SMs::CONN_INTERVAL_MIN} ..................................................
#define CONN_INTERVAL_MIN 200U

//${SMs::CONN_INTERVAL_MAX} ..................................................
#define CONN_INTERVAL_MAX 300U

//${SMs::CONN_RESPONDER_LATENCY} .............................................
#define CONN_RESPONDER_LATENCY 0U

//${SMs::CONN_TIMEOUT} .......................................................
#define CONN_TIMEOUT 500U

//${SMs::CONN_MIN_CE_LENGTH} .................................................
#define CONN_MIN_CE_LENGTH 0U

//${SMs::CONN_MAX_CE_LENGTH} .................................................
#define CONN_MAX_CE_LENGTH 0xffff

//${SMs::BSL_INVOCK_DELAY} ...................................................
#define BSL_INVOCK_DELAY (1U * 1U* 50U)

//${SMs::BSL_CHECK_STATUS_WAIT} ..............................................
#define BSL_CHECK_STATUS_WAIT (1U * 1U* 10U)

//${SMs::MASS_ERASE_DELAY} ...................................................
#define MASS_ERASE_DELAY (1U * 1U* 10U)

//${SMs::BSL_NEXT_WRITE_DELAY} ...............................................
#define BSL_NEXT_WRITE_DELAY (1U * 1U* 10U)

//${SMs::CONN_RSP_WINDOW} ....................................................
#define CONN_RSP_WINDOW (1U * 1U* 10U)
//$enddecl${SMs} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

//$declare(SMs::bt_SPC51)
//$declare(SMs::remoteSM_ctor)

//for power firmware update debugings
//#define LED_DEB (void)0U;
#define LED_DEB sl_led_toggle(&sl_led_led0);


extern QMsm * const QMsm_bt_SPC51_p; // opaque pointer to the remoteSM HSM

#endif // HISTORY_H_
