//$file${SMs::./Scr::remoteSM.c} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: remote_SM.qm
// File:  ${SMs::./Scr::remoteSM.c}
//
// This code has been generated by QM 7.0.1 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// Copyright (c) 2005 Quantum Leaps, LLC. All rights reserved.
//
//                 ____________________________________
//                /                                   /
//               /    GGGGGGG    PPPPPPPP   LL       /
//              /   GG     GG   PP     PP  LL       /
//             /   GG          PP     PP  LL       /
//            /   GG   GGGGG  PPPPPPPP   LL       /
//           /   GG      GG  PP         LL       /
//          /     GGGGGGG   PP         LLLLLLL  /
//         /___________________________________/
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open-source software licensed under the GNU
// General Public License (GPL) as published by the Free Software Foundation
// (see <https://www.gnu.org/licenses>).
//
// NOTE:
// The GPL does NOT permit the incorporation of this code into proprietary
// programs. Please contact Quantum Leaps for commercial licensing options,
// which expressly supersede the GPL and are designed explicitly for
// closed-source distribution.
//
// Quantum Leaps contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${SMs::./Scr::remoteSM.c} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#include "em_common.h"
#include "app_assert.h"
#include "sl_bluetooth.h"
#include "app.h"
#include "qpc.h"

#include "remoteSM.h"


//$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
// Check for the minimum required QP version
#if (QP_VERSION < 730U) || (QP_VERSION != ((QP_RELEASE^4294967295U)%0x2710U))
#error qpc version 7.3.0 or higher required
#endif
//$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${SMs::remote_inst} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${SMs::remote_inst} ........................................................
static remoteSM remote_inst;
//$enddef${SMs::remote_inst} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

//static ToastOven l_oven; // the only instance of the ToastOven class

// global-scope definitions -----------------------------------------
QHsm * const remote_inst_p = &remote_inst.super; // the opaque pointer

//$define${SMs::remoteSM} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${SMs::remoteSM} ...........................................................

//${SMs::remoteSM::ctor} .....................................................
void remoteSM_ctor(remoteSM * const me) {
    //remoteSM *me = &remote_inst;
    me->advertising_set_handle = 0xff;
    QHsm_ctor(&me->super, Q_STATE_CAST(&remoteSM_initial));
}

//${SMs::remoteSM::SM} .......................................................
QState remoteSM_initial(remoteSM * const me, void const * const par) {
    //${SMs::remoteSM::SM::initial}
    (void)par; // unused parameter
    return Q_TRAN(&remoteSM_OPERATIONAL);
}

//${SMs::remoteSM::SM::OPERATIONAL} ..........................................
QState remoteSM_OPERATIONAL(remoteSM * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${SMs::remoteSM::SM::OPERATIONAL::sl_bt_evt_system_boot_id}
        case sl_bt_evt_system_boot_id: {
            me->sc = sl_bt_advertiser_create_set(&me->advertising_set_handle);
            app_assert_status(me->sc);

            // Generate data for advertising
            me->sc = sl_bt_legacy_advertiser_generate_data(me->advertising_set_handle,
                                                     sl_bt_advertiser_general_discoverable);
            app_assert_status(me->sc);


            // Set advertising interval to 100ms.
            me->sc = sl_bt_advertiser_set_timing(
                                                me->advertising_set_handle,
                                                160, // min. adv. interval (milliseconds * 1.6)
                                                160, // max. adv. interval (milliseconds * 1.6)
                                                0,   // adv. duration
                                                0);  // max. num. adv. events
            app_assert_status(me->sc);

            // Start advertising and enable connections.
            me->sc = sl_bt_legacy_advertiser_start(me->advertising_set_handle,
                                             sl_bt_legacy_advertiser_connectable);
            app_assert_status(me->sc);

            app_log_info("Advertising....");
            status_ = Q_HANDLED();
            break;
        }
        //${SMs::remoteSM::SM::OPERATIONAL::sl_bt_evt_connection_opened_id}
        case sl_bt_evt_connection_opened_id: {
            app_log_info("Connection Opened....");

            status_ = Q_HANDLED();
            break;
        }
        //${SMs::remoteSM::SM::OPERATIONAL::sl_bt_evt_connection_closed_id}
        case sl_bt_evt_connection_closed_id: {
            me->sc = sl_bt_legacy_advertiser_generate_data(me->advertising_set_handle,
                                                     sl_bt_advertiser_general_discoverable);
            app_assert_status(me->sc);

            // Restart advertising after client has dime->sconnected.
            me->sc = sl_bt_legacy_advertiser_start(me->advertising_set_handle,
                                             sl_bt_legacy_advertiser_connectable);

            app_log_info("Connection Opened....");
            status_ = Q_HANDLED();
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}
//$enddef${SMs::remoteSM} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define(SMs::remoteSM_ctor)
