/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#ifndef __GATT_DB_H
#define __GATT_DB_H

#include "sli_bt_gattdb_def.h"

extern const sli_bt_gattdb_t gattdb;

#define gattdb_generic_attribute              1
#define gattdb_service_changed_char           3
#define gattdb_database_hash                  6
#define gattdb_client_support_features        8
#define gattdb_remoteAccess                   9
#define gattdb_Led_num                        11
#define gattdb_Percentage                     15
#define gattdb_Status                         19
#define gattdb_Send                           23
#define gattdb_device_information             25
#define gattdb_manufacturer_name_string       27
#define gattdb_model_number_string            29
#define gattdb_hardware_revision_string       31
#define gattdb_firmware_revision_string       33
#define gattdb_system_id                      35
#define gattdb_device_name                    38
#define gattdb_ota                            41
#define gattdb_ota_control                    43


#endif // __GATT_DB_H
